# Generated by Django 5.0.7 on 2024-07-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_mobileo_supplier_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ManyToManyField(to='app.item'),
        ),
    ]
